name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/hishana/domains/adminportal.hishana.com/public_html
          git config --global --add safe.directory /home/hishana/domains/adminportal.hishana.com/public_html
          git pull origin main
          composer install
          php artisan migrate --force
          git status
